apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ctn-service
  labels:
    app: ctn-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctn-service
  template:
    metadata:
      labels: 
        app: ctn-service
    spec:
      containers:
      - name: ctn-service
        image: keke65/pca_cloud_srv_ctn
        ports: 
        - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata: 
  name: ctn-service-service
spec:
  selector: 
    app: ctn-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 10002
      targetPort: 10000
