apiVersion: apps/v1
kind: Deployment
metadata: 
  name: data-service
  labels:
    app: data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels: 
        app: data-service
    spec:
      containers:
      - name: data-service
        image: keke65/pca_cloud_srv_data
        ports: 
        - containerPort: 10001
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database_url
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: dbname 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: pass
---
apiVersion: v1
kind: Service
metadata: 
  name: data-service-service
spec:
  selector: 
    app: data-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001
      nodePort: 30001
